### ISSUE TITLE
Final Vesta release for webtrees 2.0.x with webtrees v2.0.26 - Error: Class 'Fisharebest\Webtrees\DebugBar' not found

### ISSUE THREAD

**Issue by TheDutchJewel** [vesta-webtrees-2-custom-modules/vesta_classic_laf#131]
I still don't like the webtrees 2.1 version for data entry. The view is less compact than in the old version and there have been design changes that I don't find useful (e.g. issue [#4511](https://github.com/fisharebest/webtrees/issues/4511) and [#4657](https://github.com/fisharebest/webtrees/issues/4657)).

That's why I locally (localhost) still use v2.0.19..

Today I tried to test your [final Vesta release for webtrees 2.0.x](https://cissee.de/vesta.for.webtrees.2.0.final.zip) with the [latest v2.0.x version](https://github.com/fisharebest/webtrees/releases/download/2.0.26/webtrees-2.0.26.zip) (v2.0.26).

But if I enable the **vesta_classic_look_and_feel module** I get this error in webtrees:
`Error: Class 'Fisharebest\Webtrees\DebugBar' not found in D:\xampp\htdocs\webtrees20\modules_v4\vesta_classic_look_and_feel\resources\views\layouts\default_20.phtml:70 Stack trace: #0 D:\xampp\htdocs\webtrees20\app\View.php(184): include() #1 D:\xampp\htdocs\webtrees20\app\View.php(279): Fisharebest\Webtrees\View->render() #2 D:\xampp\htdocs\webtrees20\app\Helpers\functions.php(200): Fisharebest\Webtrees\View::make('layouts/default', Array) #3 D:\xampp\htdocs\webtrees20\app\Http\ViewResponseTrait.php(55): view('layouts/default', Array) #4 D:\xampp\htdocs\webtrees20\app\Http\RequestHandlers\TreePage.php(93): Fisharebest\Webtrees\Http\RequestHandlers\TreePage->viewResponse('tree-page', Array) #5 D:\xampp\htdocs\webtrees20\app\Http\Middleware\WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\TreePage->handle(Object(Nyholm\Psr7\ServerRequest)) #6 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #7 D:\xampp\htdocs\webtrees20\app\Module\HitCountFooterModule.php(157): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #8 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #9 D:\xampp\htdocs\webtrees20\app\Http\Middleware\CheckCsrf.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #10 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #11 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #12 D:\xampp\htdocs\webtrees20\app\Http\Middleware\Router.php(166): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #13 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #14 D:\xampp\htdocs\webtrees20\app\Http\Middleware\BootModules.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #15 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #16 D:\xampp\htdocs\webtrees20\app\Http\Middleware\LoadRoutes.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #17 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #18 D:\xampp\htdocs\webtrees20\app\Http\Middleware\UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #19 D:\xampp\htdocs\webtrees20\vendor\illuminate\database\Concerns\ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection)) #20 D:\xampp\htdocs\webtrees20\app\Http\Middleware\UseTransaction.php(46): Illuminate\Database\Connection->transaction(Object(Closure), 3) #21 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #22 D:\xampp\htdocs\webtrees20\app\Http\Middleware\DoHousekeeping.php(74): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #23 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #24 D:\xampp\htdocs\webtrees20\app\Http\Middleware\UseTheme.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #25 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #26 D:\xampp\htdocs\webtrees20\app\Http\Middleware\CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #27 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #28 D:\xampp\htdocs\webtrees20\app\Http\Middleware\UseLanguage.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #29 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #30 D:\xampp\htdocs\webtrees20\app\Http\Middleware\UseSession.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #31 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #32 D:\xampp\htdocs\webtrees20\app\Http\Middleware\UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #33 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #34 D:\xampp\htdocs\webtrees20\app\Http\Middleware\UseDatabase.php(117): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #35 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #36 D:\xampp\htdocs\webtrees20\app\Http\Middleware\BadBotBlocker.php(223): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #37 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #38 D:\xampp\htdocs\webtrees20\app\Http\Middleware\CompressResponse.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #39 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #40 D:\xampp\htdocs\webtrees20\app\Http\Middleware\ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #41 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #42 D:\xampp\htdocs\webtrees20\vendor\middlewares\client-ip\src\ClientIp.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #43 D:\xampp\htdocs\webtrees20\app\Http\Middleware\ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #44 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #45 D:\xampp\htdocs\webtrees20\app\Http\Middleware\HandleExceptions.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #46 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #47 D:\xampp\htdocs\webtrees20\app\Http\Middleware\BaseUrl.php(77): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #48 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #49 D:\xampp\htdocs\webtrees20\app\Http\Middleware\ReadConfigIni.php(69): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #50 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #51 D:\xampp\htdocs\webtrees20\app\Http\Middleware\SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #52 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #53 D:\xampp\htdocs\webtrees20\app\Http\Middleware\EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #54 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #55 D:\xampp\htdocs\webtrees20\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #56 D:\xampp\htdocs\webtrees20\app\Webtrees.php(239): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #57 D:\xampp\htdocs\webtrees20\app\Webtrees.php(226): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array) #58 D:\xampp\htdocs\webtrees20\index.php(44): Fisharebest\Webtrees\Webtrees->httpRequest() #59 {main}`

Tested with and wihout all other modules disabled: the problem only occurs when the **vesta_classic_look_and_feel module** is enabled.

Is it possible to fix this?

**Comment by ric2016** [comment]
I do not plan any further work on 2.0.x.

I could be persuaded to provide another "Final" release if you create a PR that fixes this issue.

In the long term I do not think it is a good idea to stay on 2.0.x anyway, the issues mentioned should be addressed (or fixed via custom modules).

**Comment by TheDutchJewel** [comment]
>I do not plan any further work on 2.0.x.

Okay. The only reason I asked is because the version you share gives a problem.

>I could be persuaded to provide another "Final" release if you create a PR that fixes this issue.

That is not an option: I am not a programmer.

>In the long term I do not think it is a good idea to stay on 2.0.x anyway, the issues mentioned should be addressed (or fixed via custom modules).

Agreed, but until then I'll keep using the old version.
