### ISSUE TITLE
error when calling webtrees via curl

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_classic_laf#133]
`
Uncaught ErrorException: Attempt to read property "name" on null in /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/modules_v4/vesta_classic_look_and_feel/resources/views/layouts/default.phtml:76
Stack trace:
#0 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/modules_v4/vesta_classic_look_and_feel/resources/views/layouts/default.phtml(76): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/View.php(183): include('...')
#2 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/View.php(278): Fisharebest\Webtrees\View->render()
#3 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#4 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/Http/ViewResponseTrait.php(54): view()
#5 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/Http/Middleware/HandleExceptions.php(170): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->viewResponse()
#6 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/app/Http/Middleware/HandleExceptions.php(98): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->httpExceptionResponse()
#7 /mnt/web109/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtreestest/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
`

That error happened when I called webtrees via a curl command:
`curl -v -XPOST -H "Content-Type: application/x-www-form-urlencoded" https://ahnentest.hartenthaler.eu/index.php`
This was done in order to test a new custom module to support CompGen Metasuche.

**Comment by hartenthaler** [comment]
My usage is a bit artificial. After disabling the Vesta LAF module there is an other error in webtrees function "Validator". I have to check that.
